import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

import Hero from "components/Hero/Hero";
import HeroList from "components/HeroList/HeroList";
import { useState } from "react";

const Home: NextPage = () => {
  const [heroList, setHeroList] = useState([]);
  const [heroSelected, setHeroSelected] = useState(null);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Hero onChange={} heroSelected={heroSelected} />
        <HeroList list={heroList} />
      </main>
    </div>
  );
};

export default Home;
